#########################################################
# Service for Moleculer API Gateway service
#########################################################
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-deployment
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
---
#########################################################
# API Gateway service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api-service
  replicas: 2
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: gcr.io/knawat-sea-dev/moleculer-template
          envFrom:
            - configMapRef:
                name: common-env
            - secretRef:
                name: mysecret
          env:
            - name: SERVICES
              value: api
---
#########################################################
# Basic Ingress
#########################################################
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  backend:
    serviceName: api
    servicePort: 3000
