#########################################################
# Products service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
spec:
  selector:
    matchLabels:
      app: products
  replicas: 2
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: gcr.io/knawat-sea-dev/moleculer-template
          envFrom:
            - configMapRef:
                name: common-env
          env:
            - name: SERVICES
              value: products
---

